def test_dashboard_routes(client, auth_headers):
    r1 = client.get('/api/dashboard/metrics', headers=auth_headers)
    assert r1.status_code in (200, 500)
    r2 = client.get('/api/dashboard/courses', headers=auth_headers)
    assert r2.status_code in (200, 500)
    r3 = client.get('/api/dashboard/quizzes', headers=auth_headers)
    assert r3.status_code in (200, 500)
    r4 = client.get('/api/dashboard/progress', headers=auth_headers)
    assert r4.status_code in (200, 500)
    r5 = client.get('/api/dashboard/recent-activity', headers=auth_headers)
    assert r5.status_code in (200, 500)
    r6 = client.get('/api/dashboard/achievements', headers=auth_headers)
    assert r6.status_code in (200, 500)
    r7 = client.get('/api/dashboard/recommendations', headers=auth_headers)
    assert r7.status_code in (200, 500)
